# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit Testing and Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checks out code
      uses: actions/checkout@v2

    - name: Docker-up
      run: |
        docker-compose up --build -d
    - name: Lint with flake8
      run: |
        docker-compose exec -T unnamed-django flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Python Tests
      working-directory: app/
      run: |
        docker-compose exec -T unnamed-django pytest 
    - name: JS Tests
      working-directory: app/
      run: |
       docker-compose exec -T unnamed-frontend bash -c "ls && npm install && CI=1 npm test"